### PR TITLE
"Searching" (filtering) project's win conditions

### PR DESCRIPTION
**Pull request by kgrimes2**
User should now be able to search for win conditions that are in a project by:

1. Navigating to the "Wins" tab
2. Clicking on the "Filter results" button
3. Typing a name (first, last, full) or some text that appears in the WC

Try it out:

1. `git clone git@github.com:Winbook-USC/winbook-ci.git`
2. Open up `docker-compose.yaml`
3. Edit the `kgrimes2/winbook-app:latest` line to `kgrimes2/winbook-app:KevinSearchWinConds`
4. `docker-compose up`
5. Access the webapp at http://localhost:4200

Some stuff I'm not sure about and would definitely like feedback on:

- Should the "Filter results" button be replaced with the filter box, and therefore remove the logic of keeping it hidden by default? Reason I wanted it hidden by default was because I thought that having two input boxes so close to each other would inevitably result in people who wanted to create WCs accidentally filtering instead, and vice versa.
- If we keep it, should the "Filter results" button be an actual button (similar to the "Download CSV" button), or does it look OK as-is? I liked the way I have it now because it was less jarring of a transition between it and the filter box, but interested in what you all think as well.

### CODE REVIEW

**Comment by frederickjjoubert** [comment]
> LGTM but here's my feedback:
> 
> 1. I think we should keep it hidden by default, when I was playing around with it I accidentally typed out a win condition after filtering and hit enter and nothing happened (I got confused by which text input to use)
> 2. A potential solution: add a  between the wc text input and the wc list, filter, sort, export, categories.

Lol I didn't realize you could add a "hr" on a github comment.

**Comment by kgrimes2** [comment]
@frederickjjoubert great feedback, thanks! I'll add the "hr" and see if I can resolve these conflicts.

**Comment by kgrimes2** [comment]
@frederickjjoubert @idelgado2 Updated Docker image: `kgrimes2/winbook-app:KevinSearchWinCondsV2`

So to test you should be able to just update step (3) above to this new image.

- Resolved merge conflicts
- Added a line separating the WC input box and the filter/export/sort fields

**Comment by kgrimes2** [comment]
Good catch, Jacques, thanks! I'll get it fixed.

**Comment by kgrimes2** [comment]
@frederickjjoubert @idelgado2 Updated per suggestions. New image here: `kgrimes2/winbook-app:KevinSearchWinCondsV3`

**Pull request merged**
